### ISSUE TITLE
Add "Create new dashboard" button on top of the home page

### ISSUE THREAD

**Issue by bettiolo** [dashy-io/dashy-io.github.io#4]
Text: Create new dashboard
Link: http://client.dashy.io
Target: _blank

**Comment by mtt87** [comment]
Created, I need to optimise it for mobile

**Comment by bettiolo** [comment]
It does not look right on Firefox

**Comment by mtt87** [comment]
I've created them in the main space, I think is better now to catch the eye and make people try
